version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf1234
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: do.spamu.lol@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      ADDR: :3000
      POSTGRES_CONN_STRING: postgres://postgres:asdf1234@db:5432/postgres
      SECRET: asdf1234
      MAX_LEVELS: 6

volumes:
  pg_data: {}
  pgadmin_data: {}