version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf1234
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      ADDR: :3000
      POSTGRES_CONN_STRING: postgres://postgres:asdf1234@db:5432/postgres
      SECRET: asdf1234

volumes:
  pg_data: {}